name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Deploy to Production Server
      run: |
        ssh user@production-server 'cd /path/to/project && git pull origin master && pkill -f app.py || true && nohup python3 app.py &'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
